version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3:10-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Install poetry
          command: pip install poetry
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run behave