version: 2.1

workflows:
  test_ui:
    jobs:
      - build_and_run:
          context:
            - dockerhub

jobs:
  build_and_run:
    docker:
      - image: cimg/3.12.1-browser
        auth:
          username: $USERNAME
          password: $API_TOKEN
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run behave