version: 2.1
jobs:
  build_and_run:
    docker:
      - image: cimg/python:3.12.1-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Run tests
          command: poetry run behave